local:
  image: brunolm/node-image:7.4.0-onbuild
  command: npm run start
  volumes:
    - ./:/usr/src/app
  ports:
    - 3000
  environment:
    NODE_ENV: development
    VIRTUAL_PORT: 3000
    VIRTUAL_HOST: test.local.codingwise.com
  links:
    - db:db

db:
  image: postgres:9.4.4
  ports:
    - '5432:5432'
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: test
